=== helderfpires/io-tools/tags/io-tools-1.2.9/wazformat/src/main/java/com/gc/iotools/fmt/formatInfo.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://io-tools.googlecode.com/format-info/" targetNamespace="http://io-tools.googlecode.com/format-info/">
    <element name="formats" type="tns:formatsType">
    </element>

    <complexType name="formatsType">
    	<sequence>
    		<element name="format" maxOccurs="unbounded" minOccurs="0">
    			<complexType>
    				<sequence>
    					<element maxOccurs="1" minOccurs="1" name="name"
    						type="string">
    					</element>
    					<element maxOccurs="1" minOccurs="0"
    						name="description" type="string">
    					</element>
    					<element maxOccurs="1" minOccurs="0"
    						name="mimetypes" type="string">
    					</element>
    					<element maxOccurs="1" minOccurs="0"
    						name="extensions" type="string" />
    					<element name="superseeds" type="string" maxOccurs="1" minOccurs="0"></element>
    				</sequence>
    			</complexType>
      </element>
    	</sequence>
    </complexType>
</schema>

=== helderfpires/io-tools/tags/io-tools-1.2.9/wazformat/src/main/java/com/gc/iotools/fmt/formatInfo.xml
<formats xmlns="http://io-tools.googlecode.com/format-info/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://io-tools.googlecode.com/format-info/ formatInfo.xsd ">
	<format>
		<name>AVI</name>
		<description>Audio/Video Interleaved</description>
		<mimetypes></mimetypes>
		<extensions>avi</extensions>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions>zip</extensions>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
	<format>
		<name>ZIP</name>
		<description></description>
		<mimetypes></mimetypes>
		<extensions></extensions>
		<superseeds></superseeds>
	</format>
</formats>
